### PR TITLE
encode base for unicode dirname

### PR DESCRIPTION
**Pull request by simonsmh**

### CODE REVIEW

**Comment by spencerwooo** [comment]
so you actually have a root with non-unicode characters?

**Comment by simonsmh** [comment]
应该说是非ascii字符做文件夹名的问题，比如base设在中文文件夹上时就能复现了

**Comment by spencerwooo** [comment]
哎，为啥非得用非英文路径折磨自己呢……

**Review by spencerwooo — APPROVED** [review]

**Comment by spencerwooo** [comment]
Seems that this is the cause for issue #34 which is also what I myself is experiencing. Hence, reverting this PR.

**Pull request merged**
